version: '3.8'

services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      NODE_ENV: production

    env_file:
      - .env

  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

volumes:
  database: